import './globals.css'
import { Inter } from 'next/font/google'

// @ts-ignore
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '喵爸的小作坊',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
